title: "Ruth Constance Zénon Négrite"
logo: img/photo_profil.jpg
description: "Portfolio BTS SIO SISR – Infrastructure, Systèmes, Réseaux & Cybersécurité"
show_downloads: false
theme: jekyll-theme-minimal
lang: fr

# Informations supplémentaires
author: "Ruth Constance Zénon Négrite"
email: "tonemail@email.com"

# Réseaux (si tu veux les afficher plus tard)
linkedin_username: ruth-zenon-negrite
github_username: tonpseudoGitHub
